name: bookly_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.12.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sectra
      fonts:
        - asset: assets/fonts/GT_Sectra_Fine_Regular.ttf
